# Generated by Django 5.2.8 on 2025-11-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
