# Generated by Django 5.2.8 on 2025-12-24 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reting',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
