# Generated by Django 5.2.8 on 2025-12-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_review_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reting',
            new_name='rating',
        ),
    ]
