# Generated by Django 5.2.8 on 2026-01-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_reting_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
